apiVersion: apps/v1
kind: Deployment
metadata:
  name: roommate-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roommate-recommender
  template:
    metadata:
      labels:
        app: roommate-recommender
    spec:
      containers:
      - name: streamlit
        image: roommate-recommender:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
