apiVersion: v1
kind: Service
metadata:
  name: roommate-app
spec:
  selector:
    app: roommate-app
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30545
  type: NodePort
