apiVersion: v1
kind: Service
metadata:
  name: roommate-recommender-service
spec:
  selector:
    app: roommate-recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer  # Or NodePort depending on your cluster
