apiVersion: apps/v1
kind: Deployment
metadata:
  name: roommate-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roommate-app
  template:
    metadata:
      labels:
        app: roommate-app
    spec:
      containers:
        - name: streamlit
          image: ashvinjoby/roommate-app:latest
          ports:
            - containerPort: 8501

---

apiVersion: v1
kind: Service
metadata:
  name: roommate-service
spec:
  type: NodePort
  selector:
    app: roommate-app
  ports:
    - port: 80
      targetPort: 8501
