apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohabgrid-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cohabgrid
  template:
    metadata:
      labels:
        app: cohabgrid
    spec:
      containers:
      - name: cohabgrid
        image: cohabgrid-app:latest
        ports:
        - containerPort: 80