apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohabgrid-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cohabgrid
  template:
    metadata:
      labels:
        app: cohabgrid
    spec:
      containers:
      - name: cohabgrid-container
        image: cohabgrid-app
        ports:
        - containerPort: 8501
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
          failureThreshold: 6
