apiVersion: v1
kind: Service
metadata:
  name: cohabgrid-service
spec:
  type: NodePort  # Needed for `minikube service` to expose URL
  selector:
    app: cohabgrid
  ports:
    - protocol: TCP
      port: 80          # Exposed service port
      targetPort: 8501  # Your app’s internal container port
