apiVersion: v1
kind: Service
metadata:
  name: cohabgrid-service
  labels:
    app: cohabgrid
spec:
  selector:
    app: cohabgrid
  type: NodePort
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30080